# Generated by Django 4.2.7 on 2025-07-05 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureschedule',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.lectureschedule'),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='professor',
            field=models.CharField(blank=True, help_text='Professor name', max_length=100),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='room',
            field=models.CharField(blank=True, help_text='Classroom or location', max_length=100),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Timetable', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
