# Generated by Django 4.2.7 on 2025-07-08 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_lectureschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_regular',
            field=models.BooleanField(default=False, help_text='Is this a regular course with scheduled lectures?'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='last_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slot_type', models.CharField(choices=[('study', 'Study Session'), ('meeting', 'Meeting'), ('gym', 'Gym/Exercise'), ('personal', 'Personal Time'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_slots', to='tracker.timetable')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('timetable', 'date', 'start_time')},
            },
        ),
    ]
